{% set name = "django-treebeard" %}
{% set version = "4.2.0" %}
{% set sha256 = "c1830d6e98618f524af654e084cd40e9449fdd1c9959f6fe679f08d54b964ba9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - django >=1.8

test:
  imports:
    - treebeard

about:
  home: https://github.com/django-treebeard/django-treebeard
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Efficient tree implementations for Django'
  description: |
    django-treebeard is a library that implements efficient 
    tree implementations for the Django Web Framework 1.8 and later.
  doc_url: http://django-treebeard.readthedocs.io/en/latest/
  dev_url: https://github.com/django-treebeard/django-treebeard

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
