travis:
  secure:
    BINSTAR_TOKEN: iW4wByFtKpKxvCijoqDjYOzSJg16qhYT/3FVe+pOB2tHFvefljEDN66D/uTxcy3Ll8BCJvaUO8yV7zIvCW2twxu6HBpnlmKSZkv5AO7HidwRZxIpUZog7DI1x4MbkGIMNANyjWVcqk0AkgBwaM3tMyMgTcpILYcVbE1nmok2wc/TXO8yKrmzrdglYmwFuvsMsIhCZ2hS64XvNR9lJvbNj5ndZEGa8PQ8obP+CTFRZmF1PV2ejgapej4qXUZTLL6hx2AKy/KPTaiAFYG1n7Gx+TtERXr86LpQBArd3YPYiz476SuxvJ5WsvPZRoGYntep2271V5rgb3SaTGh/7Kl1KophvzaAu32p4vVtcxcft0dZjWNK+CoU57q+7JDrzf1DjbfV75HidFjBDhTijibvPisgA6GeKnd8VxnGb+FLU5/N5t/+kYXE+RRnnFd39cOObjQ9cH+LcWQwg9v5gojOOwdRIXp6tpp/Br8SUm4nzlwawpvLKSyskpnWh51/lD8h/i+wgV/Z+togKKYFY1bqu8vJERRG1mpqPco+xq9o7lY3Qkdn7WvCrZqE9orD3bmggHGt7W1NJOC0gAjafNVRce4ZX41wOg3WpCqXnnkEraNLBjzMZzIZcgeSId/8/EHRiVSjz06sfZB9Pt1Dbftd8rq7ot3cBGEdWm9qMtXsP2s=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
