travis:
  secure:
    BINSTAR_TOKEN: q3zdrrOnDj/6NRybokHB2/cZ8bHi4SHX+NIiMi/0oMQhD5Aw07ZgBapomW/KsZlfFZCiQohYhVnAx8oTe0D3rnerfJhmsot1HzzdlEkJweYfqm6b5lJ0CN8vNENH1dt9alvvxtM4Rn9BzCL5jluwOUTv7zQb93bDaFLHxFlydLgndzEPh5LJwt+eOlpJmg+gkHd1zHoRfsB5Xj4qy6mY7JZLd9pu83iutWjsQ3OniIBw6FwpprYwxHMwUD2USYNRCXauZXFwhsD8hWvVno7pf7EvGmdUoEcjO5scfah6uW3Z+dmkS0NPUfXRbEdBm39wWDAOrNEcaQmd7rXsfsyOy9pUSSK3RkghhNbY7JPYlPQVAKcsiLYpZtMxTUsPGAmRgRRhARZNAaV22b/Ug6uwOFlLLMYcuAmXPXgOBz5QLl2yOLhzreLLwNhF8MnWCelQp2RmxgVDOrQXcYenNpt6+BCDCQmLcGvg4OA+CliXHU6KGd461xYuHD3f2teX2SCPcf4qjjj2M2c2xtXQgAz+Y9zYH1N3n78gAkSHa1n9wRMpzRNDVN0fmZK6vA/Q7iJBnB0ui1FrXNtKkr8H1VnGZVz376rqKUeU+gjjDCP2Z6PPVS7woQ+pByrg8H7hHEvCoBwzdX1khnWAv9xU/VelSCRiOC0hNP0vATgdjxnNyoQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
