travis:
  secure:
    BINSTAR_TOKEN: K7ng4sqt08PpdQfqy8pbULzcbZbr6GZjz44EZ9BJ64T8G0ZZTWX3YSEuyjAC60LQyVgaGrR1caho2q7bf9pKAx4DeZEL6SwzWeHky5RoYL95Ho5lSHTQT08BLiHulROyOxjUklFzymuq/7lCFhK+cAxNpC3g23qF5ofk5zAQJZKQD1gKgdyVUnaUYdy9Gu+r+WaRQyUjCQ+t59+FcdVZVZXhVOGTMdCIPJrZi5tS5up2n5+BIGZ3aMRCaUoUaPxdTiXiSjoTUZwjGEz3J1ZefmR65QftRmmrXDrV6rEB7kbQp3mronqW9523GVoqDWRMrTNF9aOo84Fao3jMeYjVEe0VC4fw7+outYNxmoreVy3webv19ptN14vgpNOduJZsceJQzywt5ZGXx/Uvu/GKrE8UlTZwp6L4cgiJz3CsYaAJY6ZAzmepFzQPry//cLdYTk6CpF5pBMZiwRPAqQIiTcOFMfzLbG9LIo/oYVekfVuAGqnk5WUBPs+7FSRPHG9Ko+9If5HwTdOe74YByFoiHvX8NB4XZbIvDP+WPH7CM2/m1Bi+jZe9dAZRHeFs7JMYiARdxvBMM+qFMxaptHQqPsoA9U1Vjvt8nGCQbAaDBj8kZ0IWmKXg3GAYpG6jshWcwDSPXvI6ZN2LXMyq17j79Ws9Xxak9OC9jwx0QWUiF4c=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
